import { parse } from "@babel/parser";
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
const records = new Map();
for (const path of ["src/main.jsx", "src/commerce.jsx"]) {
  const source = readFileSync(path, "utf8");
  const tree = parse(source, { sourceType: "module", plugins: ["jsx"] });
  function walk(node, section = "Site") {
    if (!node || typeof node !== "object") return;
    if (node.type === "FunctionDeclaration") section = node.id?.name || section;
    if (
      path.endsWith("commerce.jsx") &&
      ![
        "Checkout",
        "OrderPage",
        "OrdersList",
        "Status",
        "CommerceHeading",
        "ErrorMessage",
      ].includes(section) &&
      section !== "Site"
    )
      return;
    if (
      node.type === "CallExpression" &&
      node.callee?.name === "t" &&
      node.arguments.length === 2 &&
      node.arguments.every((a) => a.type === "StringLiteral")
    ) {
      const [tr, en] = node.arguments.map((a) => a.value);
      const key = createHash("sha256")
        .update(tr + "\u0000" + en)
        .digest("hex")
        .slice(0, 16);
      records.set(key, { key, section, tr, en });
    }
    if (
      node.type === "ArrayExpression" &&
      node.elements.length === 2 &&
      node.elements.every((a) => a?.type === "StringLiteral")
    ) {
      const [tr, en] = node.elements.map((a) => a.value);
      const key = createHash("sha256")
        .update(tr + "\u0000" + en)
        .digest("hex")
        .slice(0, 16);
      records.set(key, { key, section, tr, en });
    }
    if (node.type === "JSXOpeningElement" && node.name?.name === "SiteText") {
      const value = node.attributes.find((a) => a.name?.name === "tr")?.value;
      const tr = value?.expression?.value ?? value?.value;
      if (typeof tr === "string") {
        const en = tr;
        const key = createHash("sha256")
          .update(tr + "\u0000" + en)
          .digest("hex")
          .slice(0, 16);
        records.set(key, { key, section, tr, en });
      }
    }
    for (const value of Object.values(node)) {
      if (Array.isArray(value)) {
        for (const child of value) walk(child, section);
      } else if (value && typeof value === "object") walk(value, section);
    }
  }
  walk(tree);
}
writeFileSync(
  "src/copy-defaults.js",
  "// Generated by scripts/extract-copy.mjs. Stable translation IDs.\nexport const copyDefaults = " +
    JSON.stringify([...records.values()], null, 2) +
    ";\n",
);
console.log("Editable site copy:", records.size, "entries.");
