export const products = [
  {
    id: "survival-spawn",
    category: "Minecraft",
    image: "spawn.png",
    title: ["Sarı Temalı Survival Spawn", "Yellow Themed Survival Spawn"],
    description: [
      "Sunucunuz için 300×300 blok boyutunda, detaylı ve keşfetmeye hazır bir başlangıç dünyası.",
      "A detailed 300×300 block spawn, ready to become the starting point of your server.",
    ],
    price: 0,
    tags: ["300 × 300", "1.20+", "WorldEdit"],
  },
  {
    id: "dfbng-stone",
    category: "Minecraft",
    image: "minecraft.jpg",
    title: ["dfbng Stone", "dfbng Stone"],
    description: [
      "Özelleştirilebilir metin taşı sistemi, dahili coin marketi ve oyuncu sıralaması.",
      "Customizable stone system with a built-in coin shop and player leaderboard.",
    ],
    price: 500,
    oldPrice: 1000,
    tags: ["Paper / Spigot", "1.21+", "Java 21"],
  },
  {
    id: "fallen-angel",
    category: "Web",
    image: "angel.png",
    title: ["Fallen Angel Paketi", "Fallen Angel Pack"],
    description: [
      "İki devasa kanat, bir hale ve özel yay tasarımıyla projenize farklı bir kimlik katın.",
      "Give your project a unique identity with two enormous wings, a halo and a custom bow design.",
    ],
    price: 350,
    tags: ["3D", "Resource pack", "Design"],
  },
];
export const serviceItems = [
  [
    "minecraft-plugin",
    "Minecraft Plugin",
    "Minecraft Plugin",
    "Sunucu konseptinize özel, yüksek performanslı eklenti ve modlar.",
    "High-performance plugins and mods built around your server.",
    "Blocks",
  ],
  [
    "fivem-script",
    "FiveM Script & Framework",
    "FiveM Scripts & Framework",
    "QBCore ve ESX uyumlu roleplay, meslek ve envanter sistemleri.",
    "QBCore and ESX compatible roleplay, jobs and inventory systems.",
    "Gamepad2",
  ],
  [
    "discord-bot",
    "Discord Bot",
    "Discord Bot",
    "Destek talepleri, otomasyon, moderasyon ve topluluk yönetimi.",
    "Tickets, automation, moderation and community management.",
    "Bot",
  ],
  [
    "web-market",
    "Web Sitesi & Market",
    "Website & Store",
    "Sunucunuza entegre web marketler, yönetim panelleri ve web siteleri.",
    "Server-integrated web stores, control panels and websites.",
    "Globe",
  ],
  [
    "design",
    "Görsel Tasarım",
    "Visual Design",
    "Launcher, logo, banner ve oyun içi arayüz tasarımları.",
    "Launchers, logos, banners and in-game interface design.",
    "Palette",
  ],
  [
    "free",
    "Ücretsiz Danışmanlık",
    "Free Consulting",
    "Projeniz için doğru teknolojileri birlikte seçelim.",
    "Let’s choose the right technology for your project together.",
    "MessagesSquare",
  ],
];
export const faqs = [
  [
    "dfbng software tam olarak ne yapıyor?",
    "What exactly does dfbng software do?",
    "Minecraft, FiveM, Discord ve web projeleri için yazılım geliştiriyoruz. Hazır paketlerden tamamen size özel projelere kadar ihtiyaç duyduğunuz teknik çözümleri bir araya getiriyoruz.",
    "We build software for Minecraft, FiveM, Discord and the web, bringing together ready-made packages and fully custom projects.",
  ],
  [
    "Yardıma ihtiyacım olduğunda ne yapabilirim?",
    "What can I do when I need help?",
    "İletişim sayfasından destek talebi oluşturabilirsiniz. Ürün adını, kullandığınız sürümü ve sorunun ayrıntılarını eklemeniz yeterli.",
    "Create a support request on our contact page. Include your product name, version and a description of the issue.",
  ],
  [
    "İlk defa sunucu açıyorum, kullanabilir miyim?",
    "Can I use this if I am opening my first server?",
    "Elbette. Başlangıç rehberlerimiz adım adım kurulum sürecini anlatır. Ek yardıma ihtiyaç duyarsanız iletişim formundan bize ulaşabilirsiniz.",
    "Absolutely. Our getting-started guides walk you through setup. If you need more help, use our contact form.",
  ],
  [
    "Ürünler güncelleme alıyor mu?",
    "Do products receive updates?",
    "Sürüm uyumluluğunu ve güncelleme bilgilerini ürün detayından takip edebilirsiniz. Projenize özel bakım ihtiyaçlarını sipariş talebinizde belirtebilirsiniz.",
    "Check compatibility and version details on each product page. Include your maintenance needs in your custom order request.",
  ],
  [
    "Sıfırdan özel bir proje yaptırabilir miyim?",
    "Can I request a custom project from scratch?",
    "Evet. Özel sipariş formunda fikrinizi, ihtiyacınız olan özellikleri ve bütçenizi paylaşın. Projenizin kapsamını birlikte belirleyelim.",
    "Yes. Share your idea, required features and budget in the custom order form so we can define the project scope.",
  ],
  [
    "Lisans ve yenileme süreci nasıl işliyor?",
    "How do licensing and renewals work?",
    "Lisans kapsamı ürün ve proje teklifinde belirtilir. Ödeme havale / EFT ile yapılır. Yönetici onayından sonra ürün dosyası hesabınızdan indirilebilir.",
    "License terms are specified in the product or project proposal. Pay by bank transfer. After administrator approval, your uploaded product file can be downloaded from your account.",
  ],
];
export const docs = [
  [
    "start",
    "Başlangıç",
    "Getting started",
    "dfbng software ile başlayın",
    "Get started with dfbng software",
    "Projenize uygun ürünü mağazadan seçin. Ürün sayfasındaki sürüm ve platform gereksinimlerini kontrol edin. Özel bir çözüme ihtiyacınız varsa özel sipariş formunu doldurun.",
    "Find the right product in our store. Check its version and platform requirements. For a custom solution, complete the custom order form.",
  ],
  [
    "minecraft",
    "Minecraft kurulumu",
    "Minecraft setup",
    "Sunucunuzu hazırlayın",
    "Prepare your server",
    "Paper veya Spigot sunucunuzu durdurun ve dünyanızın yedeğini alın. Uyumlu eklenti dosyasını plugins klasörüne yerleştirin. Sunucunuzu yeniden başlatın ve oluşan yapılandırma dosyasını düzenleyin.",
    "Stop your Paper or Spigot server and back up your world. Put the compatible plugin file in the plugins folder. Restart your server and edit the generated configuration.",
  ],
  [
    "discord",
    "Discord bot kurulumu",
    "Discord bot setup",
    "Topluluğunuzu bağlayın",
    "Connect your community",
    "Discord Developer Portal üzerinden bir uygulama ve bot oluşturun. Yalnızca ihtiyaç duyduğunuz izinleri etkinleştirin. Bot tokeninizi gizli tutun ve sunucu ortam değişkenlerinde saklayın.",
    "Create an application and bot in the Discord Developer Portal. Enable only the permissions you need. Keep your bot token private and store it in server environment variables.",
  ],
  [
    "web",
    "Web market kurulumu",
    "Web store setup",
    "Mağazanızı yapılandırın",
    "Configure your store",
    "Alan adınızı ve barındırma hizmetinizi hazırlayın. Ürünlerinizi ve kategorilerinizi düzenleyin. Canlıya geçmeden önce ödeme sağlayıcınızı bağlayın ve test siparişinizi tamamlayın.",
    "Prepare your domain and hosting. Set up products and categories. Before going live, connect a payment provider and complete a test order.",
  ],
  [
    "support",
    "Sorun giderme",
    "Troubleshooting",
    "Birlikte çözelim",
    "Let’s solve it together",
    "Önce sunucu konsolundaki hata mesajını ve ürün sürümünü kontrol edin. Çakışan eklentileri test ortamında devre dışı bırakın. Sorun devam ederse hata ayrıntılarıyla bir destek talebi oluşturun.",
    "First check the error in your server console and your product version. Disable conflicting plugins in a test environment. If the issue persists, create a support request with the error details.",
  ],
];
